---
- name: Cleanup containers
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
  - name: Ensure containers are removed
    docker_container:
      name: "{{item}}"
      state: absent
    with_items:
    - master-container
    - node-container-1
    - node-container-2